name: Fitscale
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.17.2
  cloud_functions: ^4.7.6
  google_sign_in: ^6.2.1
  email_validator: ^2.1.17
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  pedometer: ^4.0.0
  permission_handler: ^11.3.0
  google_fonts: ^6.2.1
  provider: ^6.0.0
  connectivity_plus: ^5.0.2
  flutter_svg: ^2.0.9
  fl_chart: ^0.66.0
  confetti: ^0.7.0
  resend: ^1.0.0
  http: ^1.1.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  pigeon: ^24.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/Fitscale_background.png
    - assets/Fitscale_LOGO.png
    - assets/google_logo.png
    - assets/diet_images/
